front_book_container:
  container_name: book_front_content
  ports:
    - '3001:4200'
  command: |
    bash -c "
    npm install
    npm start"
  working_dir: /book
  volumes:
    - './:/book'

  image: spefalex/book:1.1
